[package]
name = "podchiver"
version = "0.1.0"
authors = ["Simon Morgan <sjm@sjm.io>"]
edition = "2024"

[dependencies]
clap = { version = "4", features = ["cargo"] }
opml = "1"
ureq = "3"
rss = "2"
url = "2"
html-escape = "0.2"
chrono = "0.4"
